version: '3.7'

services:
  ollama: # New service for running the Dockerfile in /ollama
    image: ollama/ollama:0.5.5
    pull_policy: always
    container_name: ollama
    networks:
      - overlay
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - '11435:11434' # will be accessible in http://localhost:11435
    volumes:
      - ./models:/models  # Mount the directory with the trained model
      - ./.ollama:/root/.ollama
    tty: true
    entrypoint: [ "/bin/sh", "/models/run_ollama.sh" ] # Loading the finetuned Mistral with the GGUF file
    runtime: nvidia
  text-embeddings-rerank:
    image: ghcr.io/huggingface/text-embeddings-inference:1.6
    restart: always
    runtime: nvidia
    ports:
      - "8111:80"
    volumes:
      - ./ktem_app_data_text_embeddings_rerank:/data
    command: --model-id BAAI/bge-reranker-v2-m3 --pooling mean
    networks:
      - overlay
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=${TZ:-Europe/Luxembourg}
  unstructured-api:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:0.0.9
    restart: always
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
      - PORT=${PORT:-8000}
    ports:
      - '8000:8000'
    networks:
      - overlay
  web-rag:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    hostname: "web-rag"
    networks:
      - overlay
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
#      - API_KEY=${API_KEY}
#      - OPENAI_API_BASE=${OPENAI_API_BASE}
#      - GRAPHRAG_API_BASE=${GRAPHRAG_API_BASE}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#      - GRAPHRAG_API_KEY=${GRAPHRAG_API_KEY}
#      - GRAPHRAG_EMBEDDING_MODEL=${GRAPHRAG_EMBEDDING_MODEL}
#      - GRAPHRAG_LLM_MODEL=${GRAPHRAG_LLM_MODEL}
      - GRADIO_SERVER_NAME=${GRADIO_SERVER_PORT:-0.0.0.0}
      - GRADIO_SERVER_PORT=${GRADIO_SERVER_PORT:-6574}
      - LOCAL_MODEL=${LOCAL_MODEL:-EuroLLM-9B-Instruct}
      - KH_DEMO_MODE=${KH_DEMO_MODE:-false}
      - KH_OLLAMA_URL=${KH_OLLAMA_URL:-http://ollama:11434/v1/}
      - KH_APP_NAME=${KH_APP_NAME:-Web-rag}
      - KH_APP_VERSION=${KH_APP_VERSION:-0.0.4}
      - LOCAL_MODEL_EMBEDDINGS=${LOCAL_MODEL_EMBEDDINGS:-bge-m3}
      - UNSTRUCTURED_URL=http://unstructured-api:8000
      - TEI_RERANKING=http://text-embeddings-rerank:80
      - KH_FEATURE_USER_MANAGEMENT=true
      - KH_FEATURE_USER_MANAGEMENT_ADMIN=greatest-user
      - KH_FEATURE_USER_MANAGEMENT_PASSWORD=6JSK8B5jS180sOVGB3EV0Tg
      - PDFJS_VERSION_DIST="pdfjs-4.0.379-dist"
    ports:
      - '6574:6574'
    volumes:
      - ./ktem_app_data:/app/ktem_app_data
networks:
  overlay:
    driver: "bridge"