version: '3.7'

services:
  oprichat-rag:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    hostname: "oprichat-rag"
    networks:
      - overlay
    environment:
      - TZ=${TZ:-Europe/Luxembourg}
      - API_KEY=${API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - GRAPHRAG_API_BASE=${GRAPHRAG_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GRAPHRAG_API_KEY=${GRAPHRAG_API_KEY}
      - GRAPHRAG_EMBEDDING_MODEL=${GRAPHRAG_EMBEDDING_MODEL}
      - GRAPHRAG_LLM_MODEL=${GRAPHRAG_LLM_MODEL}
      - GRADIO_SERVER_NAME=${GRADIO_SERVER_PORT:-0.0.0.0}
      - GRADIO_SERVER_PORT=${GRADIO_SERVER_PORT:-6574}
    ports:
      - '6574:6574'
    volumes:
      - ./ktem_app_data:/app/ktem_app_data
networks:
  overlay:
    driver: "bridge"